---
title: "Deutschkurs A2"
output:
 html_document:
   toc: true
   toc_depth: 3
   toc_float:
    collapsed: false
    smooth_scroll: false

---

<style type="text/css">

body{ /* Normal  */
      font-size: 15px;
  }
td {  /* Table  */
  
}
h1.title {
  font-size: 40px;
  color: DarkRed;
}
h1 { /* Header 1 */
  font-size: 35px;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 30px;
  color: DarkBlue;
}
h3 { /* Header 3 */
  font-size: 25px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
}
h4 {
	font-size: 23px;
	color: Blue;
}
h5 {
	font-size: 20px;
	color: DarkGreen;
}
code.r{ /* Code block */
    font-size: 13px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 13px;
}

.thumbnail:hover {
    position:relative;
    width:1000px;
    height:auto;
    display:block;
    z-index:999;
}

</style>


## Schreiben
### Anrede und Grußformel
#### 最尊敬(不太熟，不認識) Sie
* **Sehr geehrter Herr/Frau** + (姓氏) <->  Mit Freundlichen Grüßen + (自己的全名)
   
#### 第二熟(熟悉的長輩) Sie
* **Liebe Frau / Lieber Herr** + (姓氏) <-> Viele Grüße + (自己的全名)
  
#### 朋友 Du
* **Liebe(女) / Lieber(男)** + (名字) <-> Liebe Grüße + (名字)
  
#### 非常熟 Du
* **Hallo / Hi** + (名字) <-> Tschau / Tschüs / Bis Bald + (名字)
  
### 文章內容
#### 萬用
* Ich bin ja einverstanden. 我贊成 / Ich bin für deine Meinung.
* Lange nicht gesehen! / Lange nichts von dir gehört.
* Ich freue mich sehr auf die Reise.
* Vielen Dank für die Einladung. Wir haben viel Spaß mit dir gehabt.


  
#### 句型
* Ich möchte + TIME + mit + PERSON (Dativ.) zusammen + VERB.
* Ich finde ..... gut / Interessant / super, weil + ...... + VERB.
* Ich freue mich auf ... (Akkusativ.) .
* Ich finde, dass ... + VERB.
* Es ist gut / wichtig, dass ... + VERB.
* Ich finde (nicht ) gut / wichtig, dass ... + VERB.

#### 沒去赴約
* Ich bin zu Hause geblieben, weil ich Fieber hatte.  
* Ich habe meine Eltern besucht.
* Mein Hals tut mir weh. / Ich habe Kopfschmerzen. / Ich habe eine Erkältung. / Ich fühle mich nicht wohl.
* Mein Auto ist kaputt.

  
#### 約人
* Hast du Lust, mit mir ins Kino zu gehen?
* Wir müssen mal am Abend etwas trinken gehen und von alten Zeiten reden.
* Wir treffen uns bei mir zu hause. Ich freue mich auf Ihren Besuch.
